#!/usr/bin/env bash
# Usage: 
#   req1 report ==> sumamrzes results
#   rq1         ==> regenerates results, then summarizes

DATA=../../../moot/optimize
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$HOME/tmp/$(basename "$0")"
tmp=/tmp/rq0

if [ -z "$1" ]; then
  rq="old"
else
  rq="$1"
fi

generates() {
  generate 16 $DATA/c*/SS-[C-G]*.csv
  generate 16 $DATA/h*/Health-ClosedIssues000[06].csv
  generate 16 $DATA/p*/x*.csv
  generate 16 $DATA/m*/auto93.csv
}

generate() {
  local max_jobs=$1; shift

  for f in "$@"; do
    name="$(basename "$f" .csv)"
    echo "Running: $name" >&2
    out_file="$tmp/$name.csv"

    python3 -B "$DIR/../ezr.py" -f "$f" --$rq > "$out_file" &
    python3 -B "$DIR/../ezr.py" -B 40 -f "$f" --tree 

    while (( $(jobs -r | wc -l) >= max_jobs )); do
      sleep 1
    done
  done

  wait
}

mkdir -p $tmp
rm -f $tmp/*
generates

echo $rq `date`
cat "$tmp"/*.csv > "$out"
(cat "$out" | gawk -F, '{ print $(NF), $0 }' | sort -n -k1,1 | cut -d' ' -f2- 
cat "$out" | gawk -F, -f $DIR/rq1.awk ) | column -s, -t | grep --color A

