(setf *read-default-float-format* 'double-float)
#+sbcl (declaim (sb-ext:muffle-conditions warning style-warning))
(defvar *p* 2) (defvar *few* 128) (defvar *start* 4) (defvar *stop* 50)
(load "slice.lisp")
(defun atom-of (s)
  (let ((n (ignore-errors (with-input-from-string (in s) (read in)))))
    (if (numberp n) n s)))
(defun split (s &aux (out nil) (cur ""))
  (loop for ch across s do
    (if (char= ch #\,) (progn (push cur out) (setf cur ""))
        (setf cur (format nil "~a~a" cur ch))))
  (push cur out) (nreverse out))
(defun slurp (f)
  (with-open-file (in f)
    (loop for line = (read-line in nil) while line
          unless (string= (string-trim " " line) "")
          collect (split (string-trim '(#\return #\newline) line)))))
(let* ((raw (slurp "data.csv"))
       (src (cons (car raw)
                  (mapcar (lambda (r) (coerce (mapcar #'atom-of r) 'vector))
                          (cdr raw))))
       (tb (make-table src)) (rows (tbl-rows tb))
       (rv (coerce rows 'vector)))
  (format t "n ~a x [~{~a~^, ~}] y [~{~a~^, ~}]~%" (length rows) (tbl-x tb)
          (mapcar (lambda (kv) (format nil "(~a, ~a)" (car kv) (cdr kv)))
                  (tbl-y tb)))
  (format t "ymu ~,6f~%" (ymu tb rows))
  (format t "ydist0 ~,6f~%" (ydist tb (aref rv 0)))
  (format t "xdist01 ~,6f~%" (xdist tb (aref rv 0) (aref rv 1)))
  (format t "div ~{~,6f~^ ~}~%"
          (loop for c across (tbl-cols tb) when c collect (float (div c) 1d0)))
  (format t "mids ~{~a~^ ~}~%"
          (loop for (at . v) in (mids tb)
                collect (format nil "~a:~,6f" at (float v 1d0))))
  (let ((g (mapcar (lambda (l) (mapcar (lambda (s) (float (atom-of s) 1d0)) l))
                   (slurp "gauss.txt"))))
    (format t "same ~a ~a~%"
            (if (same (first g) (second g)) 1 0)
            (if (same (first g) (third g)) 1 0)))
  (let ((t0 (get-internal-real-time)) (s 0d0) (s2 0d0)
        (r1 (parse-integer (second sb-ext:*posix-argv*)))
        (r2 (parse-integer (third sb-ext:*posix-argv*))))
    (dotimes (rep r1)
      (loop for i from 0 below 120 do
        (loop for j from (1+ i) below 120 do
          (incf s (xdist tb (aref rv i) (aref rv j))))))
    (format t "W1 ~,6f~%" s)
    (dotimes (rep r2) (incf s2 (ydist tb (car (acquire tb)))))
    (format t "W2 ~,6f~%" s2)
    (format t "SEED ~a~%" *seed*)
    (format *error-output* "secs ~,3f~%"
            (/ (- (get-internal-real-time) t0)
               internal-time-units-per-second))))
