;;; ## Macros
; $slot reads as (ats i 'slot); users of $ must bind `i`
(eval-when (:compile-toplevel :load-toplevel :execute)
  (set-macro-character #\$
    (lambda (stream ch)
      (declare (ignore ch)) `(ats i ',(read stream t nil t)))))
(defmacro ? (x k &rest ks)
  (if ks `(? (ats ,x ',k) ,@ks) `(ats ,x ',k)))
(defun ats (x k &optional d) (declare (ignore d)) (slot-value x k))
(defun (setf ats) (v x k) (setf (slot-value x k) v))
(defmacro aif (test then &optional else)
  `(let ((it ,test)) (if it ,then ,else)))
;;; ## Structs
(defconstant +tiny+ 1d-32)
(defvar *seed* 1)
(defstruct num (n 0) (mu 0d0) (m2 0d0))
(defstruct sym (has nil))          ; alist, in insertion order
(defstruct tbl rows cols x y names klass mids)
; Next 0..n from a 16807 Lehmer generator
(defun rand (&optional (n 1))
  (setf *seed* (mod (* 16807 *seed*) 2147483647))
  (* n (/ *seed* 2147483647d0)))
; Fisher-Yates, driven by the seeded rand
(defun shuffle (lst &aux (v (coerce lst 'vector)))
  (loop for i from (1- (length v)) downto 1 do
    (rotatef (elt v i) (elt v (floor (rand (1+ i))))))
  (coerce v 'list))
;;; ## Columns
(defmethod sd ((i num)) (if (< $n 2) 0d0 (sqrt (/ $m2 (1- $n)))))
; add returns the column; inc=-1 undoes
(defmethod add ((i sym) v &optional (inc 1))
  (unless (equal v "?")
    (aif (assoc v $has :test #'equal)
         (incf (cdr it) inc)
         (setf $has (append $has (list (cons v inc))))))
  i)
(defmethod add ((i num) v &optional (inc 1))
  (unless (equal v "?")
    (incf $n inc)
    (let ((d (- v $mu)))
      (incf $mu (/ (* inc d) (max 1 $n)))
      (setf $m2 (max 0d0 (+ $m2 (* inc d (- v $mu)))))))
  i)
(defun adds (lst &optional (i (make-num)))
  (dolist (v lst i) (add i v)))
(defmethod size ((i num)) $n)
(defmethod size ((i sym)) (reduce #'+ $has :key #'cdr))
(defmethod div ((i num)) (sd i))
(defmethod div ((i sym))
  (let ((n (size i)))
    (- (loop for (nil . v) in $has when (> v 0)
             sum (* (/ v n) (log (/ v n) 2))))))
(defmethod mid ((i num)) $mu)
(defmethod mid ((i sym))
  (let ((best (car $has)))
    (dolist (kv $has (car best))
      (when (> (cdr kv) (cdr best)) (setf best kv)))))
(defmethod norm ((i num) v)
  (let ((z (/ (- v $mu) (+ +tiny+ (sd i)))))
    (/ 1 (+ 1 (exp (* -1.7d0 (max -3 (min 3 z))))))))
;;; ## Tables
; inc=-1 pops the last row
(defun add-row (i &optional row (inc 1))
  (setf (tbl-mids i) nil)
  (if (> inc 0)
      (setf (tbl-rows i) (append (tbl-rows i) (list row)))
      (setf row (car (last (tbl-rows i)))
            (tbl-rows i) (butlast (tbl-rows i))))
  (loop for at from 0 for c across (tbl-cols i)
        when c do (add c (elt row at) inc))
  row)
(defun make-table (src &aux (names (car src)))
  (let ((i (make-tbl :names names
                     :cols (make-array (length names)
                                       :initial-element nil))))
    (loop for at from 0 for s in names
          for last = (char s (1- (length s))) do
      (unless (char= last #\X)
        (setf (elt (tbl-cols i) at)
              (if (upper-case-p (char s 0)) (make-num) (make-sym)))
        (cond ((char= last #\!) (setf (tbl-klass i) at))
              ((find last "+-")
               (setf (tbl-y i)
                     (append (tbl-y i)
                             (list (cons at (if (char= last #\+) 1 0))))))
              (t (setf (tbl-x i) (append (tbl-x i) (list at)))))))
    (dolist (row (cdr src) i) (add-row i row))))
(defun clone (i &optional rows) (make-table (cons (tbl-names i) rows)))
; x centroid; cached until rows change
(defun mids (i)
  (or (tbl-mids i)
      (setf (tbl-mids i)
            (loop for at in (tbl-x i)
                  collect (cons at (mid (elt (tbl-cols i) at)))))))
;;; ## Distance
(defun mink (gaps)
  (expt (/ (loop for g in gaps sum (expt g *p*)) (length gaps))
        (/ 1d0 *p*)))
(defun ydist (i row)
  (mink (loop for (at . w) in (tbl-y i)
              collect (abs (- (norm (elt (tbl-cols i) at)
                                    (elt row at)) w)))))
(defun dist1 (c a b)
  (cond ((or (equal a "?") (equal b "?")) 1)
        ((sym-p c) (if (equal a b) 0 1))
        (t (abs (- (norm c a) (norm c b))))))
(defun xdist (i row m)
  (mink (loop for at in (tbl-x i)
              collect (dist1 (elt (tbl-cols i) at) (elt row at)
                             (if (listp m) (cdr (assoc at m))
                                           (elt m at))))))
(defun ymu (i rows)
  (/ (loop for r in rows sum (ydist i r)) (length rows)))
(defun ymids (i rows)
  (loop for (at) in (tbl-y i)
        collect (/ (loop for r in rows sum (elt r at)) (length rows))))
;;; ## Acquire
; near best, far from rest
(defun centroid (i best rest)
  (lambda (z) (- (xdist i z (mids rest)) (xdist i z (mids best)))))
; keep best pool near sqrt
(defun label (i best rest row)
  (add-row best row)
  (setf (tbl-rows best)
        (stable-sort (tbl-rows best) #'<
                     :key (lambda (z) (ydist i z))))
  (let ((b (length (tbl-rows best))) (r (length (tbl-rows rest))))
    (when (> b (sqrt (+ 1 b r))) (add-row rest (add-row best nil -1)))))
; pop the top scorer
(defun acquire (i &optional cap (score #'centroid))
  (let ((best (clone i)) (rest (clone i))
        (todo (subseq (shuffle (tbl-rows i)) 0 *few*)) f)
    (dotimes (k *start*)
      (label i best rest (car (last todo)))
      (setf todo (butlast todo)))
    (setf cap (or cap *stop*))
    (loop while (and todo (< (+ (length (tbl-rows best))
                                (length (tbl-rows rest))) cap)) do
      (setf f (funcall score i best rest)
            todo (stable-sort todo #'< :key f))
      (label i best rest (car (last todo)))
      (setf todo (butlast todo)))
    (append (tbl-rows best) (tbl-rows rest))))
;;; ## Stats
; gap vs pooled sd, floored
(defun cohen (xs ys &optional (d 0.35d0) (eps 0))
  (let* ((a (adds xs)) (b (adds ys))
         (pool (/ (+ (* (1- (num-n a)) (expt (sd a) 2))
                     (* (1- (num-n b)) (expt (sd b) 2)))
                  (- (+ (num-n a) (num-n b)) 2))))
    (<= (abs (- (num-mu a) (num-mu b))) (max eps (* d (sqrt pool))))))
; sorted in. rank imbalance ok?
(defun cliffs (xs ys &optional (d 0.197d0))
  (let ((gt 0) (lt 0) (j 0) (k 0) (ys (coerce ys 'vector)))
    (dolist (x xs)
      (loop while (and (< j (length ys)) (< (aref ys j) x))
            do (incf j) (setf k j))
      (loop while (and (< k (length ys)) (<= (aref ys k) x)) do (incf k))
      (incf gt j) (incf lt (- (length ys) k)))
    (<= (/ (abs (- gt lt)) (* (length xs) (length ys))) d)))
; sorted in. 95% kolmogorov-smirnov
(defun ks (xs ys &optional (a 1.36d0))
  (let* ((xs (coerce xs 'vector)) (ys (coerce ys 'vector))
         (n (length xs)) (m (length ys)) (i 0) (j 0) (d 0) v)
    (loop while (and (< i n) (< j m)) do
      (setf v (min (aref xs i) (aref ys j)))
      (loop while (and (< i n) (<= (aref xs i) v)) do (incf i))
      (loop while (and (< j m) (<= (aref ys j) v)) do (incf j))
      (setf d (max d (abs (- (/ i n) (/ j m))))))
    (<= d (* a (sqrt (/ (+ n m) (* n m) 1d0))))))
; indistinguishable, by all three
(defun same (xs ys &optional (eps 0))
  (setf xs (sort (copy-list xs) #'<) ys (sort (copy-list ys) #'<))
  (and (cliffs xs ys) (ks xs ys) (cohen xs ys 0.35d0 eps)))
