#!/usr/bin/env bash
## [why]  commit everything and push
msg=$1
[ -n "$msg" ] || read -rp "Reason? " msg
git add -A
git diff-index --quiet HEAD -- || git commit -qm "${msg:-saving}"
git push -q -u origin HEAD
git status -sb
