-- # Coding AI Experiments
-- 
-- Get the code
-- 
--     git clone http://github.com/timm/ezr
-- 
-- Make sure you select the right branch:
-- 
--       % git branch -r
--       origin/24Jun14
--       origin/24feb28
--       origin/24feb6
--       origin/24may19
--       origin/25may12
--       origin/HEAD -> origin/main
--       origin/Stable-EMSE-paper
--       origin/main
--       origin/sneak
-- 
-- You will told which `branch` to go to use in lectures
-- 
--      git checkout branch
-- 
-- Once you get there, make sure the code runs
-- 
--     cd ezr/tests
--     . ../etc/h
--     lua code.lua # <== maybe python3.12 code.py
-- 
-- This should  print some help text.
-- 
-- ## Roll your own
-- 
-- Copy `tests/Code.lua` to `tests/myCode.lua` (maybe `myCode.py`).
-- 
-- Edit that tile to do anything ant all with my code.
-- 
-- Run the code, add the output as a comment string at bottom of that code.
-- Note, you may have to do tricky things with pathnames (e.g. adding "../"). The file `tests/Makefile` 
-- has a command `test` that handles that for lua:
-- 
--      -include ../Makefile
--      one?=Code
--      
--      lua: docs2tests $(one).lua
--      	LUA_PATH='../src/?.lua;;' lua $(one).lua
-- 
-- With the code, the command
-- 
--     make one=Maths lua
-- 
-- will update all the `tests/*.lua` files (from any `docs/[A-Z]*.md` files), then
-- runs lua with `LUA_PATH`
-- 
-- **TODO** What dies the equivalent rule in Python look like? So code in `/tests` can read
-- source Python files from `/src` (hint: [read the manual](https://www.geeksforgeeks.org/sys-path-in-python/#)?
-- 
-- **SUBMIT** `tests/Makefile`
-- 
-- 
