-include  ../Makefile
DATA=~/gits/moot/optimize/misc/auto93.csv

sa      :; python3 -B sa.py     $$RANDOM $(DATA)
locals  :; python3 -B locals.py $$RANDOM $(DATA)
kmeans  :; python3 -B kmeans.py $$RANDOM $(DATA)
cluster :; python3 -B cluster.py $$RANDOM $(DATA)
