= Intelligent Scripting: 101 tips and tricks for software engineers
Tim Menzies  <timm@ieee.org>  
:stylesheet: ezr.css
:toc: 
:toc-title:  
 
==  Working Smarter, not Harder

Some kinds of AI are very hard-- hard to build, hard to change, hard to understand. 
Currently, everyone's favorite large language model (used in generative AI) has 70 trillion parameters (and this
is expected to grow larger in the near future). Such models are so expensive to build
and tune that only a handful of large organizations can attempt it. And good luck 
looking inside trying to understand how those systems work.


But not all AI is  generative AI- so not all AI is hard AI. With the right tips
and tricks, software engineers can quickly code tools they are readily understandable
for all manner of AI tasks (like optimization, prediction, classification, planning, monitoring, explanation, anomaly detection,
privacy, data sharing. and everything else discussed below). 


For example, consider an explanation system for 
semi-supervised multi-objective   sequential model optimization. Does that sound like
a complex task? Well, it isn't. This document show how to build that system in under
300 lines of Python using: 

 
- 45 scripting tips and tricks;
- 34 SE tips and tricks;
- 22 AI tips and tricks.

So have a read, see what you think. I use this code for teaching graduate AI and SE, as well as training my Ph.D. students
on how to AI easier (usually for some SE applications). You could use this code for all manner of things
such as quickly delivering an initial prototype. Or, indeed, or working out that all you need is that prototype, since it does most of what you need.

Share and enjoy. And if I missed any tips and tricks, then I'd love to hear about it. Drop me a line!

 
== Main

Here's how you say "`Hello, World!`" in Prawn:

 
----
include::ezr.py[tag=cli]
----
<1> asdsadasasa asdasd  asdasddasas
<2> asdasdsdasds 

== Conclusion

That's all, folks!
