= Easier AI Engineering: 101 tips and tricls
Tim Menzies <timm@ieee.org>
:reproducible:
:stylesheet: ezr.css
//:sidebar: sidebar
:toc: manual
:listing-caption: Listing
:source-highlighter: rouge
:rouge-style:  github 
//:pdf-page-layout: landscape
//:pdf-themesdir: ./
//:pdf-theme: some
// Uncomment next line to add a title page (or set doctype to book)
//:title-page:
// Uncomment next line to set page size (default is A4)
//:pdf-page-size: Letter
 
==   Take it easy

Some kinds of AI are very hard-- hard to build, hard to change, hard to understand. 
Currently, everyone's favorite large language model has 70 trillion parameters (and this
is expected to grow larger in the near future). Such models are so expensive to build
and tune that only a handful of large organizations can attempt it. And good luck 
looking  trying to understand how those systems work.

But not all AI is  way. There are  other kinds of useful AI tools that programmers
can understand and quickly build and modify. For example, consider an explanation system for 
semi-supervised multi-objectve sequential model optimzation. Does that sound like
a complex task? Well, it isn't. This doucment show how to build that system in under
300 lines of Python. As we shall see, this code is also good for XXX. Not bad 

See,
after 30 years of work in SE and AI, I know all the tricks that make
it real simple to apply SE principles to AI. This document divide those tricks into:

- 23 scripting tips and tricks;
- 41 SE tips and tricks;
- 32 AI tips and tricks.

I use this code for teachin graduate AI and SE, as well as training my Ph.D. students
on how to AI easier (usually for SE applications).



[square]
* item 1
* item 2
* item 3

== Main

Here's how you say "`Hello, World!`" in Prawn:

.Create a basic PDF document using Prawn
[source,python]
----
include::ezr.py[tag=cli]
----
<1> asdsadasasa asdasd  asdasddasas
<2> asdasdsdasds 

== Conclusion

That's all, folks!
