name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.13'}
      - run: git clone --depth 1 https://github.com/timm/moot $HOME/gits/moot
      - run: python3 ezr_eg.py --all
