name: tests
on: [push, pull_request]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - run: git clone --depth 1 https://github.com/timm/moot $HOME/gits/moot
      - run: pip install pytest
      - run: pytest ezeg.py
